class AulaTDD{
    Somar = function Somar(a, b) {
        return a + b
    }

    // Somar = (...args) => args.reduce((x, value) => x + value, 0);
    // Multiplicar = (...args) => args.reduce((x, value) => x * value, 1);
}

module.exports = {
    AulaTDD
};


// class Math{
//     Somar = function Somar(...args){
//         return args.reduce((x, value) => x + value, 0);
//     }
// }

//const Aula = new AulaTDD();
//console.log(Aula.Somar(3,5))
//console.log(Aula.Multiplicar(3,5))
